Cufon.replace('h2, h3, h4, h5, h6', { hover: 'true' } );
Cufon.replace('.main-menu-wrapper > ul > li', { hover: true, hoverables: { li: true }, ignore: { ul: true } } );
Cufon.replace('.breaking-wrapper p', { hover: 'true' } );
Cufon.replace('.sexyslider-title a', { textShadow: '#000 0 1px', hover: 'true' } );
Cufon.replace('.homepage-slider #navigation a', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.homepage-slider #control a span', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.homepage-title', { hover: 'true' } );
Cufon.replace('.homepage-block-1 .main-title span', { hover: 'true' } );
Cufon.replace('.layout-1 .title', { hover: 'true' } );
Cufon.replace('.layout-2 .title .text', { hover: 'true' } );
Cufon.replace('.layout-3 .title', { hover: 'true' } );
Cufon.replace('.layout-5 .title', { hover: 'true' } );
Cufon.replace('.main-footer .purchase', { hover: 'true' } );
Cufon.replace('.pages a', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.pages span', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.sidebar-title b', { hover: 'true' } );
Cufon.replace('.sidebar-title2 b', { hover: 'true' } );
Cufon.replace('.sidebar-title3 b', { hover: 'true' } );
Cufon.replace('.sidebar-title4 b', { hover: 'true' } );
Cufon.replace('.sidebar-title5 b', { hover: 'true' } );
Cufon.replace('.btn-1', { hover: 'true' } );
Cufon.replace('.tab-1', { hover: 'true' } );
Cufon.replace('.blog-slider-wrapper .image a', { hover: 'true' } );
Cufon.replace('blockquote', { hover: 'true' } );
Cufon.replace('.post-title b', { hover: 'true' } );
Cufon.replace('.comments-item .user', { hover: 'true' } );
Cufon.replace('.post-subtitle b', { hover: 'true' } );
Cufon.replace('.post .btn-1 span', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.post .btn-2 span', { textShadow: '#fff 0 1px', hover: 'true' } );
Cufon.replace('.no-comments span', { hover: 'true' } );
Cufon.replace('.text-logo', { hover: 'true' } );
Cufon.replace('.sexyslider-blog-title b', { hover: 'true' } );
Cufon.replace('.layout-4 .layout-4-title b', { hover: 'true' } );