//v29 © 2012 Tynt

Tynt=window.Tynt||[];
if(typeof Tynt.TIL=="undefined"){(function(){var Ha=function(){var h=document,k=h.body,p=h.documentElement,Y=eval("/*@cc_on!@*/false"),Z=function(a,b){for(var c="",f=0;f<b;f++)c+=a;return c},w=Z("a",50),r=(Tynt.e||"")+"ic.tynt.com",la=(Tynt.e||"")+"de.tynt.com/deb/?id="+w,x=function(){return(new Date).getTime()},q=function(a){return a.replace(/^\s+|\s+$/g,"")},M=function(a,b){for(var c in a)if(a.hasOwnProperty(c))b[c]=a[c]},z=function(a,b,c){a=h.createElement(a);M(b,a);M(c,a.style);return a},ma=function(a){for(var b=
{},c=a.length,f=[],d=0;d<c;d++)if(!b[a[d]]){b[a[d]]=true;f.push(a[d])}return f},$;$=window.addEventListener?function(a,b,c){a.addEventListener(b,c,false)}:function(a,b,c){a.attachEvent("on"+b,c)};var N=function(a,b){var c=location.hostname.split("."),f=2;do{var d=c.slice(c.length-f,c.length).join(".");h.cookie=a+";path=/;domain=."+d+";"+b;f++}while(h.cookie.indexOf(a)==-1&&f<=c.length);if(h.cookie.indexOf(a)==-1)h.cookie=a+";path=/;"+b},na=function(a){h.readyState=="complete"?a():$(window,"load",
function(){setTimeout(function(){if(typeof h.readyState=="undefined"&&!Y)h.readyState="complete";a()},10)})},n=function(a,b){var c=[],f=function(d,e){var i="http://"+d.replace("id="+w,"id="+ma(Tynt).join("~"));if(i.indexOf(r+"/b/p?")>-1&&typeof Tynt.b=="string")i+="&b="+Tynt.b;var j=new Image(1,1);if(e)j.onerror=e;j.src=i};n=function(d,e){c.push([d,e])};na(function(){n=f;for(var d=0;d<c.length;d++)n(c[d][0],c[d][1]);c=null});n(a,b)},aa=function(a){var b=[],c="",f;for(f in a)if(a.hasOwnProperty(f)){b.push(c,
f,"=",a[f]);c="&"}return b.join("")},O=function(a){for(var b=0,c=a.length<100?a.length:100,f=0;f<c;f++)b+=a.charCodeAt(f);a=Math.floor(Math.random()*3844);c=Math.abs(x()-12281184E5);return ba(c,7)+ba((b+a)%3844,2)},ca=function(a){if(a<62)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);else{var b=Math.floor(a/62);a=a-b*62;return b>=62?ca(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)}},ba=function(a,b){var c=ca(a);return Z("0",b-c.length)+c},da=function(a){return(a=q(a))?a.split(/\s+/i).length:0},P=q((h.title||location.hostname).toString()).replace(RegExp(location.hash,"g"),""),ea=function(){for(var a=h.getElementsByTagName("link"),b=0;b<a.length;b++)if(a[b].getAttribute("rel")&&a[b].getAttribute("rel").match("canonical")&&a[b].getAttribute("href")){a=a[b].getAttribute("href");b=location.protocol+"//"+
location.host+location.pathname;var c=h.getElementsByTagName("base")[0];if(c)if(c=c.getAttribute("href"))b=c;if(!a.match(/^http/)){if(a.charAt(0)=="/"){c=b.indexOf("/",9);if(c>-1)b=b.slice(0,c)}else{c=b.lastIndexOf("/");if(c>9)b=b.slice(0,c+1);else b+="/"}a=b+a}return a}return""},E=function(a){return a.replace(/^https?:\/\//,"")},Q=function(a,b){for(var c=b+"=",f=a.split(";"),d=0;d<f.length;d++){for(var e=f[d];e.charAt(0)==" ";)e=e.substring(1,e.length);if(e.indexOf(c)==0)return e.substring(c.length,
e.length)}return null},oa=function(){var a=Q(h.cookie,"tracertraffic"),b=encodeURIComponent(E(ea())),c=h.location.hash;c=/tynt=/.test(c)?c.match(/tynt=?([^?&$#]*)/)[1]:false;var f=r+"/b/p?id="+w+(a?"&et="+a:"")+(c?"&a="+c:"")+"&ts="+x(),d=f+(b?"&cu="+b:""),e=d+(h.referrer?"&r="+encodeURIComponent(E(h.referrer)):"");a=e+"&t="+encodeURIComponent(P);n(a,function(){n(e,function(){n(d,function(){n(f)})})})},F=function(){var a=[];return function(b){for(var c=a.length-1;c>=0;c--)if(a[c]==b)return false;
a.unshift(b);a.length>3&&a.pop();return true}},pa=F(),qa=F(),ra=function(){var a,b=function(){window.removeEventListener("blur",b,false);R(a);return true};return function(c){a=c.target||c.srcElement;window.removeEventListener("blur",b,false);if(a.nodeName=="IMG"&&a.parentNode.nodeName!="A"){window.addEventListener("blur",b,false);setTimeout(function(){h.removeEventListener("blur",b,false)},1E4)}return true}}(),fa=function(a){R(a.target||a.srcElement,true)},G,ga=function(a){a=a.target||a.srcElement;
G=a.nodeName=="IMG"?a:null},S=function(){var a=function(i){return typeof i.pageX=="number"?{x:i.pageX-(p.scrollLeft?p.scrollLeft:k.scrollLeft),y:i.pageY-(p.scrollTop?p.scrollTop:k.scrollTop)}:{x:i.clientX,y:i.clientY}},b=function(i){i=a(i);return i.x<=0||i.y<=0||i.x>=k.clientWidth||i.y>=k.clientHeight},c=function(i){i=a(i);return i.x<=0||i.y<=0||i.x>=p.clientWidth||i.y>=p.clientHeight},f=function(i){return i.target.nodeName=="#document"},d=function(i){i=a(i);return i.x<=4||i.y<=4||i.x>=p.clientWidth-
4||i.y>=p.clientHeight-4},e=function(i){e=navigator.userAgent.match("MSIE")?!h.compatMode||h.compatMode.indexOf("CSS")==-1?b:c:navigator.userAgent.match("Firefox")?f:d;e(i)};return function(i){if(G&&e(i)){R(G);G=null}return true}}(),A;if(Tynt.c)A=function(){};else{Tynt.c=true;Tynt.m=[];A=function(){var a=true,b,c=function(f,d){var e={id:w,wc:da(d),c:d,f:a?1:0,t:P};M(f,e);a=false;var i=e.trace_type;delete e.trace_type;var j=e.g;delete e.g;for(var o=[],l=["id","wc","f","w","h","t","c"],m=0;m<l.length;m++){var B=
l[m],s=e[B];s&&o.push([B,encodeURIComponent(s).replace(/\'/g,"%27")]);delete e[B]}for(var t in e)if(e.hasOwnProperty(t))(l=e[t])&&o.push([t,encodeURIComponent(l).replace(/\'/g,"%27")]);e=[];m=2048-(("http://"+r+"/a/t/x#?").length+(3+j.length)+5);B=o.length;var y=s=0,u=0,T,H,U,I,J=0;for(e[J]={g:j,tp:null};s<B&&e.length<35;){T=o[s][0];t=o[s][1];U=T.length+2;H=m-U-y;if(H>0){l=t.substring(u,u+H);I=l.slice(-2).indexOf("%");if(I>-1){l=t.substring(u,u+H-2+I);y+=I+2}y+=l.length+U;u+=l.length;e[J][T]=l}else y=
m;if(y>=m){e[++J]={g:j,p:J};y=0}if(u>=t.length){s++;u=0}}e[0].tp=e.length;n(r+"/b/t/"+i+"?"+aa(e[0]));for(j=1;j<e.length;j++)n(r+"/b/x/"+i+"?"+aa(e[j]))};if(window.addEventListener){navigator.userAgent.match("Firefox/2")||k.addEventListener("copy",fa,false);window.addEventListener("mousedown",ga,false);window.addEventListener("dragleave",S,false);window.addEventListener("dragexit",S,false);h.addEventListener("contextmenu",ra,false)}else{k.attachEvent("oncopy",fa);h.getElementsByTagName("html")[0].attachEvent("ondragleave",
S);k.attachEvent("onmousedown",ga)}if(h.cookie.indexOf("tracertraffic=")!=-1)if(!h.referrer||h.referrer.indexOf(location.host)==-1)N("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT");oa();n(la);return function(f,d){if(!h.getElementById("tyntSS")){var e,i;if(d)if(!h.selection||!h.selection.createRange){e=getSelection();i=e.getRangeAt(0);e=e.toString()}else{e=h.selection.createRange();i=e.duplicate();e=e.text}var j=f.src;if(j&&!e&&qa(j))c({g:O(j),trace_type:3,w:f.width,h:f.height},j);else if(e&&
q(e).length&&f.nodeName!="TEXTAREA"&&f.nodeName!="INPUT"){j=pa(e);var o={trace_type:1};if(j)b=O(e);o.g=b;for(var l=true,m=0;m<Tynt.m.length;m++)l=l&&Tynt.m[m](o,e,i);j&&l&&c(o,e)}}}}}var K=function(a){a=a.charCodeAt(0);return 3584<=a&&a<=3711||11904<=a&&a<=12591||12688<=a&&a<=40959||63744<=a&&a<=64255||65072<=a&&a<=65103||131072<=a&&a<=173791||194560<=a&&a<=195103},ha=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;b>=0;b--){var c=a[b];c.parentNode.removeChild(c)}},C={};C.t=3;
C.p=6;C.w=7;C.f=8;var sa=function(a){a=a.match(/ixzz=?([^?$#]*)/);if(!a)return null;a=a[1].match(/&([^?$]*)/);if(Tynt.k)return Tynt.k.charAt(1);if(!a||!a[1])return null;return a[1]},ia=function(a){var b=new Date(x()+864E5);N("tracertraffic="+a.toString(),"expires="+b.toUTCString())},ta=function(){if(Tynt.v)return false;Tynt.v=true;var a=location.href.match(/ixzz=?([^?&$#]*)/),b=(a&&a.length==2?a[1]:null)||Tynt.h;if(b){a=sa(location.href);b=r+"/b/v"+["?g=",b,/\?trace_owner_view/.test(location.href)?
"&o=y":"","&id=",w,a?"&s="+a:"","&r=",encodeURIComponent(E(h.referrer)),"&ts=",x()].join("");n(b);ia(C[a]||1);return true}return false},g,ua=(Tynt.e||"")+"id.tynt.com",v,V,W,va=["","Attribution","Attribution Share Alike","Attribution No Derivatives","Attribution Non-Commercial","Attribution Non-Commercial Share Alike","Attribution Non-Commercial No Derivatives"],wa=["","http://creativecommons.org/licenses/by/3.0","http://creativecommons.org/licenses/by-sa/3.0","http://creativecommons.org/licenses/by-nd/3.0",
"http://creativecommons.org/licenses/by-nc/3.0","http://creativecommons.org/licenses/by-nc-sa/3.0","http://creativecommons.org/licenses/by-nc-nd/3.0"],xa=function(a){return(a=a.match(/axzz([^?$]*)/))&&a.length==2?a[1]:null},ya=function(a){var b=ea();b=b&&g.c!==false?b:location.href;b=b.replace(/#(i|a)xzz=?(.*)$/g,"");return b+"#"+("ixzz"+a)};F=function(a){n(r+"/b/a?g="+a+"&id="+w+"&r="+encodeURIComponent(E(h.referrer))+"&ts="+x(),function(){})};var ja=function(a){return a.replace(/&/g,"&amp;").replace(/</g,
"&lt;").replace(/>/g,"&gt;")},D=false,za=function(a){if(D)return false;D=true;var b="";if(g.a){var c=ya(a),f='<a style="color: #003399;" href="';b+=g.ap;if(g.st)b=b+f+c+'">'+ja(P)+"</a> ";if(g.su)b=b+f+c+'">'+ja(c)+"</a>";if(g.as.length>0)b=b+"\n<br>"+g.as+" ";if(g.cc>0)b=b+"\n<br>Under Creative Commons License: "+f+wa[g.cc]+'">'+va[g.cc]+"</a>"}if(g.el){if(b.length>0)b+="\n<br>";b+=g.el}if(v){if(b.length>0)b+="\n<br>";b=W?b+V+f+"http://tcr"+g.s+".tynt.com/ads/"+W+"/"+a+'">'+v+"</a>":b+V+f+"http://tcr"+
g.s+".tynt.com/ads/"+v+"/"+X+"/"+a+'">'+v+"</a>"}var d,e;d=z("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(!h.selection||!h.selection.createRange){var i=getSelection();if(i.toString())if(typeof i.setBaseAndExtent!="undefined"){var j=i.getRangeAt(0);a=z("span",{innerHTML:b});if(g.t){a.innerHTML+="<br/><br/>";d.appendChild(a);d.appendChild(j.cloneContents())}else{d.appendChild(j.cloneContents());a.innerHTML="<br/><br/>"+
a.innerHTML;d.appendChild(a)}ha(d);d.style.width=0.1;d.style.height=0.1;d.style.position="absolute";d.style.top="-1000px";d.style.left="-1001px";d.appendChild(h.createElement("br"));a=d.innerText.length;k.insertBefore(d,k.firstChild);if(d.innerText.length!=a)d.style.overflow="";i.selectAllChildren(d);setTimeout(function(){d.parentNode.removeChild(d);i.setBaseAndExtent(j.startContainer,j.startOffset,j.endContainer,j.endOffset);D=false},0)}else{e=z("div",{},{height:0,position:"absolute",top:"-1000px"});
e.innerHTML="<br>";if(g.t){k.insertBefore(e,k.firstChild);d.innerHTML=b+"<br><br>"}else{k.appendChild(e);d.innerHTML="<br>"+b+"<br>"}e.appendChild(d);a=h.createRange();a.selectNode(d);i.addRange(a);window.setTimeout(function(){e.parentNode.removeChild(e);D=false},0)}}else{var o=p.scrollLeft||k.scrollLeft,l=p.scrollTop||k.scrollTop;e=z("div",{},{overflow:"hidden",position:"absolute",left:o+20+"px",top:l+20+"px",width:"1px",height:"1px"});k.insertBefore(e,k.firstChild);var m=h.selection.createRange();
d.innerHTML=g.t?b+"<br><br>"+m.htmlText:m.htmlText+"<br><br>"+b;ha(d);e.appendChild(h.createElement("br"));e.appendChild(d);a=k.createTextRange();a.moveToElementText(d);a.select();setTimeout(function(){k.removeChild(e);if(m.text!=""){m.select();p.scrollLeft=o;k.scrollLeft=o;p.scrollTop=l;k.scrollTop=l}D=false},0)}return true},Ba=function(a,b){var c=true;if(g.a||v||g.el){var f;f=q(b);f=f.length>=2?K(f.charAt(0))||K(f.charAt(f.length-1))||K(f.charAt(f.length/2)):K(f);var d;if(d=g.h)a:{d=(d=Aa())?d.className.split(/\s+/):
[];for(var e=d.length-1;e>=0;e--)if(g.h[d[e]]!==undefined){d=g.h[d[e]];break a}d=void 0}d=d;if(d!==false&&(f&&b.replace(/\s/g,"").length>=g.aw*2||!f&&da(b)>=g.aw)||d)if(g.a||v||g.el){c=za(a.g);if(g.a)a.trace_type=0}}return c},Aa=function(){return!h.selection||!h.selection.createRange?function(){var a=getSelection().getRangeAt(0),b=a.startContainer.nodeType==3?a.startContainer.parentNode:a.startContainer;return b&&q(a.toString())==q(b.textContent)?b:null}:function(){var a=h.selection.createRange(),
b=a.duplicate();b.collapse(true);return(b=b.parentElement())&&q(a.text)==q(b.innerText)?b:null}}(),Ca=function(a){var b=a?864E5:-5E3;b=new Date(x()+b);h.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Ea=function(a){var b;a:{b=h.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=true;break a}b=false}if(!b&&Da(location)){Tynt.b=a||O(location.href);location.replace(location.href+"#axzz"+Tynt.b)}},Da=function(a){if(a.hash!="")return false;
if(typeof g.ba=="boolean"&&g.ba)g.ba=["/"];else if(!g.ba)return true;for(var b,c=g.ba.length-1;c>=0;c--){b=null;var f=g.ba[c],d=f.indexOf("/");if(d!=0){b=f.slice(0,d);f=f.slice(d)}if(!b||a.host==b)if(f.charAt(f.length-1)=="#"){if(a.pathname.indexOf(f.slice(0,-1))==0)return false}else if(a.pathname==f)return false}return true},Fa=function(a){g=Tynt.i||window.tyntVariables||{};g.s=a.s||1;g.a=!(g.a==0||a.a==0);g.cc=g.cc||a.cc||0;if(g.cc>6)g.cc=0;g.b=!!(g.b||a.b);g.aw=Math.max(g.aw||8,8);if(g.a){g.ap=
(g.ap||(typeof tyntAP!="undefined"?tyntAP:null)||"Read more:")+" ";g.as=g.as||(typeof tyntAS!="undefined"?tyntAS:null)||"";g.st=!!(g.st||a.st);g.su=!(g.su==0||a.su==0);g.sp=g.sp||a.sp;if(g.sp){W=g.spid;V=(g.spt||decodeURIComponent(a.spt||""))+" ";v=g.sp||decodeURIComponent(a.sp||"")}}},ka=function(){var a=h.title.indexOf("#ixzz");if(a>-1)h.title=h.title.substring(0,a);a=h.title.indexOf("#axzz");if(a>-1)h.title=h.title.substring(0,a)},Ga=function(){for(var a=0;a<Tynt.length;a++)if(Tynt[a]&&Tynt[a].length==
22)return Tynt[a];return null},L=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),f=0;f<c.length;f++){var d=c[f].split("=");if(d[0].indexOf("amp;")==0)d[0]=d[0].substring(4);b[d[0]]=d[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=h.getElementsByTagName("script"),b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),X=L.user||Ga();if(!X)throw Error("Error finding Tynt Insight userId. Please check your HTML for errors.");
L.user&&Tynt.push(L.user);/tracer=test/.test(location.href)&&n(ua+"/script/verify/"+X);(function(){if(/disableTracer=/.test(location.href)){var a=location.href.match(/disableTracer=([^?$]*)/)[1],b=new Date;b.setDate(a&&a=="on"?b.getDate()+365:b.getDate()-2);N("disableTracer="+(a&&a=="on"?"y":"n"),"expires="+b.toUTCString());b=z("div",{id:"TyntLocalOptOut"},{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",
paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&a=="on"?"off":"on")+" in this browser.<br>You may close this window.";k.insertBefore(b,k.firstChild)}})();if(!(/tracer=test|tracer=no_tracing|disableTracer=/.test(location.href)||/disableTracer=y/.test(h.cookie))){if(Y){ka();h.attachEvent("onpropertychange",ka)}Fa(L);var R=A();ta();Tynt.m.push(Ba);if(g.b)if(A=xa(location.href)){if("#axzz"+Q(h.cookie,"tracerabg")!=location.hash){F(A);ia(2)}}else{Ea(Q(h.cookie,
"tracerabg"));Ca(Tynt.b)}}};Tynt.TIL=function(){document.body?Ha():setTimeout(Tynt.TIL,300)}})();Tynt.TIL()};
